apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
spec:
  selector:
    app: mongodb # spec.selector.matchLabels.app from deployment
  ports:
  - port: 27017 # can be different
    targetPort: 27017
